local require = GLOBAL.require
local STRINGS = GLOBAL.STRINGS
local TUNING = GLOBAL.TUNING
local TECH = GLOBAL.TECH
local Ingredient = GLOBAL.Ingredient

PrefabFiles = { "boglurker" }

-- Creatures: tuning + strings
GLOBAL.TUNING.BOGLURKER_HEALTH = 100
GLOBAL.TUNING.BOGLURKER_DAMAGE = 20
GLOBAL.TUNING.BOGLURKER_ATTACK_PERIOD = 2
GLOBAL.TUNING.BOGLURKER_WALKSPEED = 5
GLOBAL.TUNING.BOGLURKER_SANITYAURA = -5
STRINGS.NAMES.BOGLURKER = "Bog Lurker"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOGLURKER = "Something is watching you from the reeds."
