local require = GLOBAL.require
local STRINGS = GLOBAL.STRINGS
local TUNING = GLOBAL.TUNING
local TECH = GLOBAL.TECH
local Ingredient = GLOBAL.Ingredient

PrefabFiles = { "dunestalker" }

-- Creatures: tuning + strings
GLOBAL.TUNING.DUNESTALKER_HEALTH = 150
GLOBAL.TUNING.DUNESTALKER_DAMAGE = 25
GLOBAL.TUNING.DUNESTALKER_ATTACK_PERIOD = 3
GLOBAL.TUNING.DUNESTALKER_WALKSPEED = 4
GLOBAL.TUNING.DUNESTALKER_SPIKE_COUNT = 6
GLOBAL.TUNING.DUNESTALKER_RADIUS = 6
GLOBAL.TUNING.DUNESTALKER_WALL_COUNT = 2
GLOBAL.TUNING.DUNESTALKER_GROUNDATTACK_COOLDOWN = 15
STRINGS.NAMES.DUNESTALKER = "Dune Stalker"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUNESTALKER = "Something moves just beneath the sand."
