local require = GLOBAL.require
local STRINGS = GLOBAL.STRINGS
local TUNING = GLOBAL.TUNING
local TECH = GLOBAL.TECH
local Ingredient = GLOBAL.Ingredient

PrefabFiles = { "meadowhopper", "meadowhopperherd" }

-- Creatures: tuning + strings
GLOBAL.TUNING.MEADOWHOPPER_HEALTH = 20
GLOBAL.TUNING.MEADOWHOPPER_DAMAGE = 0
GLOBAL.TUNING.MEADOWHOPPER_ATTACK_PERIOD = 3
GLOBAL.TUNING.MEADOWHOPPER_WALKSPEED = 3
GLOBAL.TUNING.MEADOWHOPPER_SANITYAURA = 3
GLOBAL.TUNING.MEADOWHOPPERHERD_MAX_SIZE = 6
GLOBAL.TUNING.MEADOWHOPPERHERD_GATHER_RANGE = 20
GLOBAL.TUNING.MEADOWHOPPERHERD_SPAWN_MIN = TUNING.TOTAL_DAY_TIME * 3
GLOBAL.TUNING.MEADOWHOPPERHERD_SPAWN_MAX = TUNING.TOTAL_DAY_TIME * 5
STRINGS.NAMES.MEADOWHOPPER = "Meadow Hopper"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MEADOWHOPPER = "A gentle critter that loves to help out around camp."
