import type { ModProject } from '../types/modProject'

export const sampleProject: ModProject = {
  meta: {
    name: 'Test Mod',
    description: 'A mod for testing',
    author: 'Tester',
    version: '1.0.0',
    allClientsRequireMod: true,
    configOptions: [
      {
        name: 'difficulty',
        label: 'Difficulty',
        options: [
          { description: 'Easy', data: 'easy' },
          { description: 'Hard', data: 'hard' },
        ],
        defaultIndex: 0,
      },
    ],
  },
  items: [
    {
      id: 'testsword',
      displayName: 'Test Sword',
      description: 'A sword for testing',
      category: 'weapon',
      weapon: { damage: 34 },
      finiteuses: { maxUses: 150 },
      recipe: {
        ingredients: [
          { prefab: 'twigs', amount: 2 },
          { prefab: 'flint', amount: 1 },
        ],
        techLevel: 'SCIENCE_ONE',
        filters: ['WEAPONS'],
      },
    },
    {
      id: 'testtrinket',
      displayName: 'Test Trinket',
      description: 'A trinket reusing a vanilla build',
      category: 'generic',
      animation: { source: 'vanilla', build: 'trinket_1' },
      recipe: {
        ingredients: [{ prefab: 'flint', amount: 1 }],
        techLevel: 'NONE',
        filters: ['TOOLS'],
      },
    },
    {
      id: 'testaxe',
      displayName: 'Test Axe',
      description: 'A tool for testing',
      category: 'tool',
      toolAction: 'CHOP',
      weapon: { damage: 27 },
      finiteuses: { maxUses: 100, ignoreCombatDurabilityLoss: true },
      recipe: {
        ingredients: [{ prefab: 'twigs', amount: 1 }, { prefab: 'flint', amount: 1 }],
        techLevel: 'NONE',
        filters: ['TOOLS'],
      },
    },
    {
      id: 'testfirestaff',
      displayName: 'Test Fire Staff',
      description: 'A ranged magic weapon for testing',
      category: 'weapon',
      weapon: {
        damage: 0,
        sanityCostOnUse: 3,
        ranged: { minRange: 6, maxRange: 10, projectilePrefab: 'fire_projectile', onHitEffect: 'ignite' },
      },
      finiteuses: { maxUses: 30 },
      equipWalkSpeedMult: 1.25,
      spellEffect: 'createLight',
      recipe: {
        ingredients: [{ prefab: 'nightmarefuel', amount: 3 }],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
      },
    },
    {
      id: 'testarmor',
      displayName: 'Test Armor',
      description: 'A body armor for testing',
      category: 'armor',
      armor: {
        condition: 450,
        absorption: 0.8,
        flammable: true,
        dapperness: -0.5,
        weakness: { tag: 'beaver', extraDamage: 5 },
        sanityLossOnHitPercent: 0.5,
      },
      finiteuses: { maxUses: 100 },
      equipWalkSpeedMult: 0.9,
      recipe: {
        ingredients: [{ prefab: 'log', amount: 4 }],
        techLevel: 'NONE',
        filters: ['ARMOUR'],
      },
    },
    {
      id: 'testfood',
      displayName: 'Test Food',
      description: 'A food item for testing',
      category: 'food',
      edible: { foodType: 'MEAT', healthValue: 3, hungerValue: 25, sanityValue: -5 },
      onEatBuff: { damageMultiplier: 0.25, durationSeconds: 120 },
      recipe: {
        ingredients: [{ prefab: 'monstermeat', amount: 1 }],
        techLevel: 'NONE',
        filters: ['COOKING'],
      },
    },
    {
      id: 'testspellbook',
      displayName: 'Test Spellbook',
      description: 'An item with a spell wheel for testing',
      category: 'generic',
      spellbook: {
        spells: [
          { label: 'Summon Light', summonPrefab: 'stafflight' },
          { label: 'Summon Fireflies', summonPrefab: 'firefly' },
        ],
      },
      recipe: {
        ingredients: [{ prefab: 'nightmarefuel', amount: 2 }],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
      },
    },
  ],
  structures: [
    {
      id: 'teststructure',
      displayName: 'Test Structure',
      description: 'A structure for testing',
      loot: [],
      recipe: {
        ingredients: [{ prefab: 'boards', amount: 4 }],
        techLevel: 'NONE',
        filters: ['STRUCTURES'],
      },
    },
  ],
  characters: [
    {
      id: 'testchar',
      gender: 'NEUTRAL',
      title: 'the tester',
      name: 'Testy',
      description: 'A character for testing',
      quote: 'I test things.',
      stats: { health: 150, hunger: 150, sanity: 200 },
      startingInventory: ['torch', 'flint'],
      speechOverrides: { ANNOUNCE_COLD: 'It is cold, for science.' },
      perks: ['freeze_immune'],
      damageMultiplier: 0.75,
      hungerRateMultiplier: 0,
      walkSpeedMultiplier: 1.25,
      foodTypeAffinities: [{ foodType: 'VEGGIE', multiplier: 1.33 }],
    },
  ],
  creatures: [
    {
      id: 'testmob',
      displayName: 'Test Mob',
      description: 'A mob for testing',
      animation: { source: 'custom' },
      stats: { health: 100, damage: 20, attackPeriod: 2, walkSpeed: 4 },
      loot: [{ prefab: 'monstermeat', chance: 1 }],
      behavior: 'hostile',
      tags: ['largecreature'],
      panicCauses: [],
    },
    {
      id: 'testspidermob',
      displayName: 'Test Spider Mob',
      description: 'A mob reusing a vanilla build',
      animation: {
        source: 'vanilla',
        build: 'spider',
        clips: { idle: 'idle', walk: 'walk', atk: 'atk', hit: 'hit', death: 'death' },
      },
      stats: { health: 80, damage: 15, attackPeriod: 2, walkSpeed: 4 },
      loot: [{ prefab: 'silk', chance: 1 }],
      behavior: 'hostile',
      tags: [],
      panicCauses: [],
    },
    {
      id: 'testhound',
      displayName: 'Test Hound',
      description: 'A mob with combat/status effects for testing',
      stats: { health: 100, damage: 20, attackPeriod: 2, walkSpeed: 6, attackRange: 4 },
      loot: [{ prefab: 'monstermeat', chance: 1 }],
      behavior: 'hostile',
      tags: [],
      sanityAura: -10,
      flammable: true,
      freezable: true,
      cookable: { product: 'cookedsmallmeat' },
      panicCauses: [],
    },
  ],
  rooms: [
    {
      id: 'TestGrove',
      terrain: 'FOREST',
      tags: ['Town'],
      requiredPrefabs: [],
      fixedPrefabs: [{ prefab: 'pighouse', count: { min: 2, max: 4 } }],
      scatter: { percent: 0.1, prefabs: [{ prefab: 'grass', weight: 0.05 }] },
      staticLayouts: [{ layoutId: 'TestGraveyard', count: { min: 1, max: 1 } }],
    },
  ],
  tasks: [
    {
      id: 'Test Island Shard',
      locks: ['NONE'],
      keysGiven: ['TIER1'],
      roomChoices: [{ roomId: 'TestGrove', count: { min: 1, max: 3 } }],
      backgroundTerrain: 'FOREST',
      backgroundRoom: undefined,
      regionId: 'testisland1',
      locations: ['forest'],
      colour: { r: 0, g: 1, b: 0, a: 1 },
    },
  ],
  staticLayouts: [
    {
      id: 'TestGraveyard',
      width: 4,
      height: 4,
      tiles: [
        [0, 0, 0, 0],
        [0, 7, 7, 0],
        [0, 7, 7, 0],
        [0, 0, 0, 0],
      ],
      objects: [{ prefab: 'gravestone', col: 1, row: 1, properties: [{ key: 'data.setepitaph', value: 'Bryce' }] }],
      layoutPosition: 'CENTER',
      startMask: 'IGNORE_IMPASSABLE_BARREN_RESERVED',
      fillMask: 'IGNORE_IMPASSABLE_BARREN_RESERVED',
    },
  ],
}
