import type { ModProject } from '../types/modProject'

export const sampleProject: ModProject = {
  meta: {
    name: 'Test Mod',
    description: 'A mod for testing',
    author: 'Tester',
    version: '1.0.0',
    allClientsRequireMod: true,
    configOptions: [
      {
        name: 'difficulty',
        label: 'Difficulty',
        options: [
          { description: 'Easy', data: 'easy' },
          { description: 'Hard', data: 'hard' },
        ],
        defaultIndex: 0,
      },
    ],
  },
  items: [
    {
      id: 'testsword',
      displayName: 'Test Sword',
      description: 'A sword for testing',
      category: 'weapon',
      weapon: { damage: 34 },
      finiteuses: { maxUses: 150 },
      recipe: {
        ingredients: [
          { prefab: 'twigs', amount: 2 },
          { prefab: 'flint', amount: 1 },
        ],
        techLevel: 'SCIENCE_ONE',
        filters: ['WEAPONS'],
        placer: false,
      },
    },
    {
      id: 'teststructure',
      displayName: 'Test Structure',
      description: 'A structure for testing',
      category: 'generic',
      recipe: {
        ingredients: [{ prefab: 'boards', amount: 4 }],
        techLevel: 'NONE',
        filters: ['STRUCTURES'],
        placer: true,
      },
    },
    {
      id: 'testtrinket',
      displayName: 'Test Trinket',
      description: 'A trinket reusing a vanilla build',
      category: 'generic',
      animation: { source: 'vanilla', build: 'trinket_1' },
      recipe: {
        ingredients: [{ prefab: 'flint', amount: 1 }],
        techLevel: 'NONE',
        filters: ['TOOLS'],
        placer: false,
      },
    },
    {
      id: 'testaxe',
      displayName: 'Test Axe',
      description: 'A tool for testing',
      category: 'tool',
      toolAction: 'CHOP',
      weapon: { damage: 27 },
      finiteuses: { maxUses: 100, ignoreCombatDurabilityLoss: true },
      recipe: {
        ingredients: [{ prefab: 'twigs', amount: 1 }, { prefab: 'flint', amount: 1 }],
        techLevel: 'NONE',
        filters: ['TOOLS'],
        placer: false,
      },
    },
    {
      id: 'testfirestaff',
      displayName: 'Test Fire Staff',
      description: 'A ranged magic weapon for testing',
      category: 'weapon',
      weapon: {
        damage: 0,
        sanityCostOnUse: 3,
        ranged: { minRange: 6, maxRange: 10, projectilePrefab: 'fire_projectile', onHitEffect: 'ignite' },
      },
      finiteuses: { maxUses: 30 },
      equipWalkSpeedMult: 1.25,
      spellEffect: 'createLight',
      recipe: {
        ingredients: [{ prefab: 'nightmarefuel', amount: 3 }],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
        placer: false,
      },
    },
    {
      id: 'testarmor',
      displayName: 'Test Armor',
      description: 'A body armor for testing',
      category: 'armor',
      armor: {
        absorption: 0.8,
        flammable: true,
        dapperness: -0.5,
        weakness: { tag: 'beaver', extraDamage: 5 },
        sanityLossOnHitPercent: 0.5,
      },
      finiteuses: { maxUses: 100 },
      equipWalkSpeedMult: 0.9,
      recipe: {
        ingredients: [{ prefab: 'log', amount: 4 }],
        techLevel: 'NONE',
        filters: ['ARMOUR'],
        placer: false,
      },
    },
  ],
  characters: [
    {
      id: 'testchar',
      gender: 'NEUTRAL',
      title: 'the tester',
      name: 'Testy',
      description: 'A character for testing',
      quote: 'I test things.',
      stats: { health: 150, hunger: 150, sanity: 200 },
      startingInventory: ['torch', 'flint'],
      speechOverrides: { ANNOUNCE_COLD: 'It is cold, for science.' },
      perks: ['no_hunger', 'faster_walk'],
    },
  ],
  creatures: [
    {
      id: 'testmob',
      displayName: 'Test Mob',
      description: 'A mob for testing',
      stats: { health: 100, damage: 20, attackPeriod: 2, walkSpeed: 4 },
      loot: [{ prefab: 'monstermeat', chance: 1 }],
      behavior: 'hostile',
      tags: ['largecreature'],
    },
    {
      id: 'testspidermob',
      displayName: 'Test Spider Mob',
      description: 'A mob reusing a vanilla build',
      animation: {
        source: 'vanilla',
        build: 'spider',
        clips: { idle: 'idle', walk: 'walk', atk: 'atk', hit: 'hit', death: 'death' },
      },
      stats: { health: 80, damage: 15, attackPeriod: 2, walkSpeed: 4 },
      loot: [{ prefab: 'silk', chance: 1 }],
      behavior: 'hostile',
      tags: [],
    },
    {
      id: 'testhound',
      displayName: 'Test Hound',
      description: 'A mob with combat/status effects for testing',
      stats: { health: 100, damage: 20, attackPeriod: 2, walkSpeed: 6, attackRange: 4 },
      loot: [{ prefab: 'monstermeat', chance: 1 }],
      behavior: 'hostile',
      tags: [],
      sanityAura: -10,
      flammable: true,
      freezable: true,
    },
  ],
}
