import type { ModProject } from '../src/types/modProject'
import { createEmptyModProject } from '../src/types/modProject'

export const pigVillage: ModProject = {
  ...createEmptyModProject(),
  meta: {
    name: 'Pig Village',
    description: 'Small houses that always have someone home, reusing a real Island Adventures creature build.',
    author: 'Tester',
    version: '1.0.0',
    allClientsRequireMod: true,
    configOptions: [],
  },
  structures: [
    {
      id: 'villagerhouse',
      displayName: 'Villager House',
      description: 'Small, tidy, and someone is always home.',
      animation: { source: 'vanilla', build: 'pig_house' },
      loot: [{ prefab: 'boards', chance: 0.5 }],
      resident: { prefab: 'villager', respawnDelayDays: 3 },
      recipe: {
        ingredients: [
          { prefab: 'boards', amount: 4 },
          { prefab: 'cutstone', amount: 2 },
        ],
        techLevel: 'NONE',
        filters: ['STRUCTURES'],
      },
    },
    {
      id: 'sawmill',
      displayName: 'Sawmill',
      description: 'Sawdust everywhere. Someone here loves their work.',
      animation: { source: 'vanilla', build: 'pig_house' },
      loot: [{ prefab: 'boards', chance: 0.5 }],
      resident: { prefab: 'lumberjack', respawnDelayDays: 3 },
      container: { source: 'own', widget: { source: 'custom', slots: 6, columns: 3 }, sideWidget: false },
      recipe: {
        ingredients: [
          { prefab: 'boards', amount: 4 },
          { prefab: 'rope', amount: 2 },
        ],
        techLevel: 'NONE',
        filters: ['STRUCTURES'],
      },
    },
    {
      id: 'quarry',
      displayName: 'Quarry',
      description: 'Dust in the air, and the steady sound of chipping stone.',
      animation: { source: 'vanilla', build: 'pig_house' },
      loot: [{ prefab: 'rocks', chance: 0.5 }],
      resident: { prefab: 'miner', respawnDelayDays: 3 },
      container: { source: 'own', widget: { source: 'custom', slots: 6, columns: 3 }, sideWidget: false },
      recipe: {
        ingredients: [
          { prefab: 'cutstone', amount: 4 },
          { prefab: 'rope', amount: 2 },
        ],
        techLevel: 'NONE',
        filters: ['STRUCTURES'],
      },
    },
    {
      id: 'farmhouse',
      displayName: 'Farmhouse',
      description: 'Rows of neat little plots, tended every morning.',
      animation: { source: 'vanilla', build: 'pig_house' },
      loot: [{ prefab: 'seeds', chance: 0.5 }],
      resident: { prefab: 'farmer', respawnDelayDays: 3 },
      container: { source: 'own', widget: { source: 'custom', slots: 6, columns: 3 }, sideWidget: false },
      recipe: {
        ingredients: [
          { prefab: 'boards', amount: 3 },
          { prefab: 'seeds', amount: 2 },
        ],
        techLevel: 'NONE',
        filters: ['STRUCTURES'],
      },
    },
    {
      id: 'barracks',
      displayName: 'Barracks',
      description: 'Quiet during the day, but always someone ready to answer a call.',
      animation: { source: 'vanilla', build: 'pig_house' },
      loot: [{ prefab: 'boards', chance: 0.5 }],
      resident: { prefab: 'guard', respawnDelayDays: 3 },
      recipe: {
        ingredients: [
          { prefab: 'boards', amount: 6 },
          { prefab: 'rope', amount: 2 },
        ],
        techLevel: 'SCIENCE_ONE',
        filters: ['STRUCTURES'],
      },
    },
  ],
  creatures: [
    {
      id: 'villager',
      displayName: 'Villager',
      description: 'Keeps to himself, mostly.',
      animation: {
        source: 'islandAdventuresShipwrecked',
        build: 'wildbore_build',
        bank: 'pigman',
        clips: { idle: 'idle', walk: 'walk', atk: 'atk', hit: 'hit', death: 'death' },
      },
      stats: { health: 100, damage: 20, attackPeriod: 2, walkSpeed: 3 },
      loot: [{ prefab: 'meat', chance: 1 }],
      behavior: 'neutral',
      tags: [],
      panicCauses: [],
    },
    {
      id: 'lumberjack',
      displayName: 'Lumberjack',
      description: 'Never without an axe close at hand.',
      animation: {
        source: 'islandAdventuresShipwrecked',
        build: 'wildbore_build',
        bank: 'pigman',
        clips: { idle: 'idle', walk: 'walk', atk: 'atk', hit: 'hit', death: 'death' },
      },
      stats: { health: 100, damage: 10, attackPeriod: 2, walkSpeed: 3 },
      loot: [{ prefab: 'meat', chance: 1 }],
      behavior: 'neutral',
      tags: [],
      panicCauses: [],
      work: { tasks: ['chopTrees'] },
    },
    {
      id: 'miner',
      displayName: 'Miner',
      description: 'Comes home covered in rock dust, every single day.',
      animation: {
        source: 'islandAdventuresShipwrecked',
        build: 'wildbore_build',
        bank: 'pigman',
        clips: { idle: 'idle', walk: 'walk', atk: 'atk', hit: 'hit', death: 'death' },
      },
      stats: { health: 100, damage: 10, attackPeriod: 2, walkSpeed: 3 },
      loot: [{ prefab: 'meat', chance: 1 }],
      behavior: 'neutral',
      tags: [],
      panicCauses: [],
      work: { tasks: ['mineRocks'] },
    },
    {
      id: 'farmer',
      displayName: 'Farmer',
      description: "Knows this land better than he knows his own name.",
      animation: {
        source: 'islandAdventuresShipwrecked',
        build: 'wildbore_build',
        bank: 'pigman',
        clips: { idle: 'idle', walk: 'walk', atk: 'atk', hit: 'hit', death: 'death' },
      },
      stats: { health: 100, damage: 10, attackPeriod: 2, walkSpeed: 3 },
      loot: [{ prefab: 'meat', chance: 1 }],
      behavior: 'neutral',
      tags: [],
      panicCauses: [],
      work: { tasks: ['harvestFarm'] },
    },
    {
      id: 'guard',
      displayName: 'Guard',
      description: "Stands a little straighter than the rest of the village.",
      animation: {
        source: 'islandAdventuresShipwrecked',
        build: 'wildbore_build',
        bank: 'pigman',
        clips: { idle: 'idle', walk: 'walk', atk: 'atk', hit: 'hit', death: 'death' },
      },
      stats: { health: 150, damage: 30, attackPeriod: 2, walkSpeed: 4 },
      loot: [{ prefab: 'meat', chance: 1 }],
      behavior: 'neutral',
      tags: [],
      panicCauses: [],
      companion: { followDistance: 5, tasks: [], defendLeader: true },
    },
  ],
}
