import type { ModProject } from '../src/types/modProject'
import { createEmptyModProject } from '../src/types/modProject'

export const viana: ModProject = {
  ...createEmptyModProject(),
  meta: {
    name: 'Viana, the Sunwitch',
    description: 'A sun-touched witch who channels her spells through a staff and a book of spells.',
    author: 'Tester',
    version: '1.0.0',
    allClientsRequireMod: true,
    configOptions: [],
  },
  items: [
    {
      id: 'solarlantern',
      displayName: 'Solar Lantern',
      description: "A lantern that only drinks from the sun — no fuel item will ever refill it, only standing in daylight will.",
      category: 'generic',
      animation: { source: 'vanilla', build: 'lantern', idleClip: 'idle_off' },
      solarLantern: { maxFuel: 100, drainPerSecond: 0.1, rechargePerSecondInSunlight: 0.3, radius: 4 },
      recipe: {
        ingredients: [
          { prefab: 'twigs', amount: 2 },
          { prefab: 'goldnugget', amount: 2 },
          { prefab: 'nightmarefuel', amount: 1 },
        ],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
      },
    },
    {
      id: 'sunstaff',
      displayName: 'Sun Staff',
      description: 'A staff that channels whatever spells are bound in her Sun Codex.',
      category: 'generic',
      animation: { source: 'vanilla', build: 'staffs', idleClip: 'yellowstaff' },
      spellbook: { source: 'linkedContainer', containerItemId: 'suncodex' },
      recipe: {
        ingredients: [
          { prefab: 'twigs', amount: 2 },
          { prefab: 'goldnugget', amount: 2 },
          { prefab: 'nightmarefuel', amount: 2 },
        ],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
      },
    },
    {
      id: 'suncodex',
      displayName: 'Sun Codex',
      description: 'Holds up to 3 spells at once — whatever is bound here is what the Sun Staff can cast.',
      category: 'generic',
      animation: { source: 'vanilla', build: 'books', idleClip: 'book_light' },
      container: {
        source: 'own',
        widget: { source: 'custom', slots: 3, columns: 3 },
        sideWidget: true,
        acceptsTag: 'spell',
      },
      recipe: {
        ingredients: [
          { prefab: 'papyrus', amount: 2 },
          { prefab: 'goldnugget', amount: 1 },
        ],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
      },
    },
    {
      id: 'emberwispspell',
      displayName: 'Ember Wisp Spell',
      description: 'Bind this in the Sun Codex to let the Sun Staff summon a warm, floating ember of light where she aims.',
      category: 'generic',
      animation: { source: 'vanilla', build: 'papyrus' },
      spellDef: { label: 'Ember Wisp', summonPrefab: 'emberlight', manaCost: 20, aimed: true },
      recipe: {
        ingredients: [
          { prefab: 'goldnugget', amount: 1 },
          { prefab: 'nightmarefuel', amount: 1 },
        ],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
      },
    },
    {
      id: 'solsticeblessingspell',
      displayName: 'Solstice Blessing Spell',
      description: 'Bind this in the Sun Codex to let the Sun Staff mend her wounds with the sun\'s warmth.',
      category: 'generic',
      animation: { source: 'vanilla', build: 'papyrus' },
      spellDef: { label: 'Solstice Blessing', healthDelta: 15, sanityDelta: 15, manaCost: 30 },
      recipe: {
        ingredients: [
          { prefab: 'petals', amount: 2 },
          { prefab: 'goldnugget', amount: 1 },
        ],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
      },
    },
    {
      id: 'sunfedspell',
      displayName: 'Sunfed Spell',
      description: 'Bind this in the Sun Codex to let the Sun Staff feed her on sunlight alone.',
      category: 'generic',
      animation: { source: 'vanilla', build: 'papyrus' },
      spellDef: { label: 'Sunfed', hungerDelta: 25, manaCost: 15 },
      recipe: {
        ingredients: [
          { prefab: 'twigs', amount: 1 },
          { prefab: 'goldnugget', amount: 1 },
        ],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
      },
    },
    {
      id: 'sunwispspell',
      displayName: 'Sun Wisp Spell',
      description: 'Bind this in the Sun Codex to let the Sun Staff call a small fire spirit to where she aims — it stays glowing by her side afterward.',
      category: 'generic',
      animation: { source: 'vanilla', build: 'papyrus' },
      spellDef: { label: 'Sun Wisp', summonPrefab: 'sunwisp', manaCost: 35, aimed: true },
      recipe: {
        ingredients: [
          { prefab: 'twigs', amount: 1 },
          { prefab: 'goldnugget', amount: 1 },
          { prefab: 'nightmarefuel', amount: 2 },
        ],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
      },
    },
    {
      id: 'solarbeamspell',
      displayName: 'Solar Beam Spell',
      description: 'Bind this in the Sun Codex to let the Sun Staff channel a beam of sunlight in front of her, burning anything it sweeps over.',
      category: 'generic',
      animation: { source: 'vanilla', build: 'papyrus' },
      spellDef: {
        label: 'Solar Beam',
        manaCost: 40,
        beam: { damagePerTick: 20, tickIntervalSeconds: 0.5, range: 10, durationSeconds: 3, telegraphSeconds: 0.5 },
      },
      recipe: {
        ingredients: [
          { prefab: 'goldnugget', amount: 2 },
          { prefab: 'nightmarefuel', amount: 2 },
        ],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
      },
    },
    {
      id: 'suntotem',
      displayName: 'Sun Totem',
      description: "Carve this and it carves back: use it to call up a Sun Orb, or dismiss the one you have. It only drinks from the sun — no fuel item will ever refill it, and the Orb fades the moment it runs dry.",
      category: 'generic',
      animation: { source: 'vanilla', build: 'moonrock_idol' },
      summonTotem: { summonPrefab: 'sunorb', maxDurability: 150, drainPerSecond: 0.1, rechargePerSecondInSunlight: 0.3 },
      recipe: {
        ingredients: [
          { prefab: 'twigs', amount: 3 },
          { prefab: 'goldnugget', amount: 2 },
          { prefab: 'nightmarefuel', amount: 2 },
        ],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
      },
    },
    {
      id: 'solarprism',
      displayName: 'Solar Prism',
      description: "Set it on the ground and activate it: under open sky by day, it drinks in sunlight. Use it on the Solar Lantern or Sun Totem to top off their charge, or use it on yourself to feed your own Solar Energy.",
      category: 'generic',
      animation: { source: 'vanilla', build: 'gems', idleClip: 'yellowgem_idle' },
      solarBattery: { maxCharge: 200, chargePerSecondInSunlight: 0.5 },
      recipe: {
        ingredients: [
          { prefab: 'goldnugget', amount: 3 },
          { prefab: 'nightmarefuel', amount: 3 },
        ],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
      },
    },
    {
      id: 'solarchakram',
      displayName: 'Solar Chakram',
      description: "Throw it and it bites five times over: on every hit it seeks out the next enemy nearby and leaps to it, up to 5 in a row, before spinning back into her hand.",
      category: 'weapon',
      animation: { source: 'vanilla', build: 'boomerang' },
      weapon: {
        damage: 20,
        chainReturn: { range: 15, speed: 20, maxChainHits: 5, searchRadius: 8, projectileClip: 'spin_loop' },
      },
      recipe: {
        ingredients: [
          { prefab: 'goldnugget', amount: 2 },
          { prefab: 'nightmarefuel', amount: 3 },
        ],
        techLevel: 'MAGIC_TWO',
        filters: ['MAGIC'],
      },
    },
  ],
  characters: [
    {
      id: 'viana',
      gender: 'FEMALE',
      title: 'the Sunwitch',
      name: 'Viana',
      description: 'She traded a life under open skies for one spent bent over spellbooks — the sun still answers when she calls.',
      quote: 'The sun lends its light. I just ask for it.',
      animation: { source: 'vanilla', build: 'wendy' },
      stats: { health: 120, hunger: 150, sanity: 220 },
      mana: { max: 100, regenPerSecond: 1, label: 'Solar Energy', badgeTint: [1, 0.75, 0.15, 1] },
      startingInventory: ['sunstaff', 'suncodex'],
      speechOverrides: {},
      perks: ['can_read_books'],
      damageMultiplier: 0.75,
      sanityDayGain: 1,
      sanityNightDrainMultiplier: 2,
      pauseHungerDuringDay: true,
      hungerNightMultiplier: 2,
      wetnessSanityPenalty: 3,
      summerStatBonus: 75,
      summerWalkSpeedBonusPercent: 15,
      winterStatPenalty: 50,
      overheat: { triggerTemp: 65, damageMultiplier: 1.5, sanityDrainPerSecond: 5, igniteChance: 0.15 },
      shadowAffinity: { damageDealtMultiplier: 1.5, damageTakenMultiplier: 1.5 },
      foodTypeAffinities: [],
    },
  ],
  creatures: [
    {
      id: 'sunorb',
      displayName: 'Sun Orb',
      description: 'A living cinder of sunlight, orbiting whoever called it up — warm, bright, and quick to defend her.',
      animation: {
        source: 'vanilla',
        build: 'flameball_fx',
        clips: { idle: 'idle_loop', walk: 'idle_loop', atk: 'idle_loop', hit: 'idle_loop', death: 'post' },
      },
      stats: { health: 150, damage: 25, attackPeriod: 2, walkSpeed: 8, attackRange: 3 },
      loot: [],
      behavior: 'neutral',
      tags: [],
      panicCauses: [],
      companion: {
        followDistance: 4,
        tasks: [],
        orbit: { radius: 3, degreesPerSecond: 45, contactDamage: { day: 25, dusk: 15, night: 10 } },
      },
      light: { radius: 10, intensity: 0.8, falloff: 0.8, colour: { r: 255, g: 140, b: 20 } },
      sanityAura: 10,
      heatAura: 40,
      invincible: true,
    },
    {
      id: 'sunwisp',
      displayName: 'Sun Wisp',
      description: 'A small fire spirit, warm and constant, that never strays far from her side.',
      animation: {
        source: 'vanilla',
        build: 'flameball_fx',
        clips: { idle: 'idle_loop', walk: 'idle_loop', atk: 'idle_loop', hit: 'idle_loop', death: 'post' },
      },
      stats: { health: 15, damage: 0, attackPeriod: 2, walkSpeed: 5 },
      loot: [],
      behavior: 'passive',
      tags: [],
      panicCauses: [],
      companion: { followDistance: 4, tasks: [] },
      light: { radius: 12, intensity: 0.8, falloff: 0.8, colour: { r: 250, g: 149, b: 18 } },
    },
  ],
}
